# Generated by Django 2.0.6 on 2018-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopost',
            name='respuesta',
            field=models.TextField(null=True),
        ),
    ]
