# Generated by Django 2.0.6 on 2018-06-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0002_auto_20180608_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviopost',
            name='fechaRespueta',
        ),
    ]
