# Generated by Django 2.0.6 on 2018-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0005_auto_20180609_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopost',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
