# Generated by Django 2.0.6 on 2018-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0006_auto_20180609_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopost',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
