# Generated by Django 2.0.6 on 2018-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0007_auto_20180609_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
