# Generated by Django 2.0.6 on 2018-06-10 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0012_auto_20180610_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gustos',
            fields=[
                ('idGusto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGusto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='enviopost',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 10, 2, 2, 6, 900484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gustocliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvioPost.EnvioPost'),
        ),
    ]
