# Generated by Django 2.0.6 on 2018-06-10 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0013_auto_20180610_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopost',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 10, 2, 4, 29, 794410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gustocliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvioPost.EnvioPost'),
        ),
    ]
