# Generated by Django 2.0.6 on 2018-06-10 02:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0014_auto_20180610_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='gustocliente',
            name='MRZ',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enviopost',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 10, 2, 32, 29, 877646, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gustocliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvioPost.EnvioPost'),
        ),
    ]
