# Generated by Django 2.0.6 on 2018-06-11 02:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioPost', '0019_auto_20180610_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopost',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 11, 2, 42, 34, 561530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gustocliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvioPost.EnvioPost'),
        ),
        migrations.AlterField(
            model_name='gustocliente',
            name='interes6',
            field=models.BooleanField(),
        ),
    ]
